### ISSUE TITLE
Windows 使用者造詞的編碼是使用 UTF-16 LE

### ISSUE THREAD

**Issue by aquastripe** [aa846301/LoL-UserTerms#1]
我載下來匯入以後發現格式不相容無法匯入
發現問題出在檔案編碼是 UTF-8 而 Windows 使用者造詞的編碼要 UTF-16 LE
另存新檔 -> 編碼改成 UTF-16 LE 問題就解決了

Repo owner 沒有這問題嗎？

**Comment by aa846301** [comment]
請問你下載的是release的檔案嗎？
因為Github預設的編碼是UTF8
所以我轉碼成UTF16LE 提供給用戶下載
直接下載的話，要手動轉碼
可以的話，也可以順便幫我測試Release的檔案

**Comment by aquastripe** [comment]
了解
我是直接 git clone。我試了一下 release 版是正確的
謝謝
